name: Hello
on:
  workflow_dispatch:
    inputs:
      jar_version:
        description: 'Latest Jar verision'
        required: true
jobs:
  Generate-Release-artifacts:
    runs-on: ubuntu-latest
    steps:
       - name: print hello world
         run: |
          echo "hello world" 
