name: Release Gatling Enterprise package  
on:
  push:
jobs:
  Generate-Release-artifacts:
    runs-on: ubuntu-latest
          
    steps:
      - name: Upload Gatling jar to Github Release
        id: changes
        run: |
          echo "terraform='hello world'" >> $GITHUB_OUTPUT
        
      - name: test
        run: echo "${{ steps.changes.outputs.terraform }}"
        
